using GradedArrays: GradedArrays
using Test: @test, @testset
@testset "Test exports" begin
    exports = [
        :AbstractGradedArray,
        :AbstractGradedMatrix,
        :AbstractSectorArray,
        :AbstractSectorDelta,
        :AbelianGradedArray,
        :AbelianGradedMatrix,
        :AbelianGradedVector,
        :UniqueSectorArray,
        :UniqueSectorDelta,
        :UniqueSectorMatrix,
        :UniqueSectorVector,
        :Data,
        :FusedGradedMatrix,
        :FusedGradedVector,
        :Fib,
        :GradedArrays,
        :GradedBlockAlgorithm,
        :GradedOneTo,
        :Ising,
        :codomain,
        :data,
        :domain,
        :dataaxes,
        :dataaxes1,
        :datalength,
        :datalengths,
        :eachdataaxis,
        :eachsectoraxis,
        :O2,
        :SectorIdentity,
        :FusedSectorMatrix,
        :FusedSectorVector,
        :SectorOneTo,
        :SectorRange,
        :SU2,
        :TrivialSector,
        :U1,
        :Z,
        :Z2,
        :dual,
        :flip,
        :gradedrange,
        :isdual,
        :sector,
        :sectoraxes,
        :sectoraxes1,
        :sectorlength,
        :sectorlengths,
        :sectors,
        :sectortype,
    ]
    @test issetequal(names(GradedArrays), exports)
end
